name: Test

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
    branches:
      - master
      - 'v*'

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-16.04, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Run tests
      run: make test
      env:
        FLIT_ROOT_INSTALL: "1"
